### ISSUE TITLE
Soll die Änderungs-Historie filterbar sein?

### ISSUE THREAD

**Issue by benjamin-hempel** [mribrgr/StuRa-Mitgliederdatenbank#10]
Soll die Historie über alle Änderungen, die an der Datenbank vorgenommen wurden, filterbar sein (z.B. nach User, Zeitpunkt, Art der Änderung, ...)?

**Comment by thrs79136** [comment]
Ja, die Historie sollte nach Amt und Person gefiltert werden können.
Priorität: niedrig

**Comment by benjamin-hempel** [comment]
Bezieht sich die Filterung nach Amt und Person auf den-/diejenigen, der/die die Änderung vorgenommen hat? Oder auf den betroffenen Datensatz?

**Comment by Yoshinonxkun** [comment]
Filtern in Änderungshistorie zu welcher Person etwas geändert wurde.
Also zu einem betroffenen Datensatz
