### ISSUE TITLE
Wireframes erstellen

### ISSUE THREAD

**Issue by thrs79136** [mribrgr/StuRa-Mitgliederdatenbank#11]
Ein erster Entwurf von den Wireframes zu den Use Cases sollte bis zum Treffen mit Robert Ringel (14.01.2020) erstellt werden.

**Comment by Yoshinonxkun** [comment]
* Loginansicht (Theresa)
* Übersicht (Mitglieder, Checklistenansicht, Ämteransicht) (Jill)
* Mitglieder- Listenansicht (Filter) ->  LOGIN VERWALTUNG (Helene)
   + Hinzufügen, Löschen
* Checklistenansicht (Stefan)
* Ämter (Stefan)
* Änderungshistorie (Benjamin)



Vorname | Nachname | nickname | Funktion | Telefonnummer | XMPP-Adresse | Mail-Adresse | s-Nummer/Mail-Adresse | Datengeheimnis | Mail-Verteiler | Kartenzugang | Schlüsselkasten | Website | Website Gruppen | Wiki | ownCloud | Adresse 


Büro
legislative Mitglieder
exekutive Mitglieder
beratende Mitglieder
beratende Mitglieder für den faranto e.V.
Pseudonyme
wohl zu löschen
von allen Ämtern zurückgetreten








https://bildungsportal.sachsen.de/opal/auth/RepositoryEntry/21511831560/CourseNode/100478865026621/Praktikum+3+-+Wireframes.pdf

Screenshot vom Tabellenkopf der Tabelle
wie soll der Login sein?

**Comment by Yoshinonxkun** [comment]
Ämter
https://www.stura.htw-dresden.de/stura/ref

**Comment by benjamin-hempel** [comment]
Überarbeitung gemäß der Informationen aus den letzten Stakeholder-Treffen erforderlich:
- Mitglieder-Listenansicht (Filter) -> LOGIN VERWALTUNG (Helene) (Hinzufügen, Löschen)
- Ämter (Stefan)

**Comment by mribrgr** [comment]
Abgeschlossen? Derzeitiger Stand? @creerm

**Comment by benjamin-hempel** [comment]
Sind noch Wireframes offen? @creerm @Jill3 @Helene3e
