### ISSUE TITLE
Aktivitätsdiagramme erstellen

### ISSUE THREAD

**Issue by thrs79136** [mribrgr/StuRa-Mitgliederdatenbank#12]
Ein erster Entwurf von den Aktivitätsdiagrammen sollte bis zum Treffen mit Robert Ringel (14.01.2020) erstellt werden.

**Comment by mribrgr** [comment]
Nutzer verwalten: @Yoshinonxkun

**Comment by mribrgr** [comment]
Mitglieder verwalten: @benjamin-hempel
