### ISSUE TITLE
Risk List erstellen

### ISSUE THREAD

**Issue by benjamin-hempel** [mribrgr/StuRa-Mitgliederdatenbank#14]
Die Risikoliste muss erstellt werden.

**Comment by Yoshinonxkun** [comment]
Ist das noch aktuell??

**Comment by benjamin-hempel** [comment]
@mribrgr

**Comment by mribrgr** [comment]
Derzeit keine weiteren Ideen, werden ansonsten fortlaufend ergänzt.

**Comment by mribrgr** [comment]
@Stefano-96 Bitte nochmal rüberschauen und danach schließen

**Comment by benjamin-hempel** [comment]
@Stefano-96 Bitte noch prüfen!
