### ISSUE TITLE
Project Plan überarbeiten

### ISSUE THREAD

**Issue by benjamin-hempel** [mribrgr/StuRa-Mitgliederdatenbank#15]
Der Projektplan muss fertiggestellt werden, da er zum Ende des Semesters abgegeben werden muss.

**Comment by benjamin-hempel** [comment]
Der Project Plan ist immer noch nicht wirklich ausgearbeitet. Dies muss bis spätestens zum Ende dieser Iteration (31.01.) geschehen, da der Project Plan Teil der Abgabe ist.

**Comment by mribrgr** [comment]
@Stefano-96 kannst du den Abteil Deployment ausarbeiten?

**Comment by Stefano-96** [comment]
Ja mach ich
