### ISSUE TITLE
Sollen Änderungen an den Systemnutzern in der Historie erscheinen?

### ISSUE THREAD

**Issue by benjamin-hempel** [mribrgr/StuRa-Mitgliederdatenbank#20]
Wenn eine/r der Administrator/innen einen Systemnutzer (jemand, der auf die Mitgliederverwaltung Zugriff hat) hinzufügt, ändert oder löscht, soll diese Änderung dann in der Historie auftauchen? Passwortänderungen würden dann natürlich nicht explizit angezeigt.

**Comment by Yoshinonxkun** [comment]
Wir können das gerne nochmal beim nächsten Treffen abklären aber ich habe es so verstanden, dass alle Änderungen da auftauchen.

**Comment by Yoshinonxkun** [comment]
Ist die Frage noch offen?

**Comment by benjamin-hempel** [comment]
Hat sich im letzten Stakeholdertreffen geklärt --> alle Änderungen sollen dort auftauchen.
