### ISSUE TITLE
Klassendiagramme anlegen

### ISSUE THREAD

**Issue by mribrgr** [mribrgr/StuRa-Mitgliederdatenbank#21]

**Comment by creerm** [comment]
@benjamin-hempel @thrs79136 Ich habe mal einen ersten Versuch eines Klassendiagramms hochgeladen. Ich denke da müsste man wegen den Mitgliederklassen (Ämtern) nochmal mit Frau von Asow sprechen.. 
@mribrgr Hab das Diagramm bzw. den Ordner aus Versehen in den falschen Ordner hochgeladen, bitte in img verschieben.

**Comment by benjamin-hempel** [comment]
Erster, überarbeiteter Entwurf gemäß Infos aus dem letzten Stakeholdertreffen: https://github.com/mribrgr/StuRa-Mitgliederdatenbank/blob/develop/docs/Klassendiagramm/KlassendiagrammEntwurf.png

Diskussion intern und mit Stakeholdern erforderlich bzw. erwünscht

**Comment by creerm** [comment]
Ich bin mir nicht sicher in welchem Zusammenhang die Klasse Aufgabe steht. Handelt es sich dabei rein um einen Abgleich von Soll und Ist für Sophia? Das hätte man dann ja vielleicht auch ohne eine eigene Klasse lösen können. Die Klasse Checkliste ist wohl sinnvoll, aber das würde man nicht auch in die Datenbank als Tabelle aufnehmen oder? Ich bin auch nicht sicher, ob man in mehreren Referaten sein kann, das müssten wir nochmal erfragen. Sonst scheint mir das auch alles ganz sinnvoll. Aber wir sollten das vielleicht eh nochmal mündlich in der Gruppe besprechen beim nächsten Treffen.

**Comment by benjamin-hempel** [comment]
Unsere Idee war, dass in der Klasse Aufgabe alle Aufgaben gespeichert sind mit Aufgaben-ID, Checklisten-ID, Bezeichnung und Abarbeitungs-Status (true/false). Das heißt, eine Checkliste besteht aus n Aufgaben. In der Klasse Checkliste würden dann die einzelnen Checklisten mit Checklisten-ID, Bezeichnung (?) und Mitglieds-ID (des Mitglieds, für welches die Checkliste abgearbeitet wird) gespeichert werden. Im Organigramm sind glaube ich auch manche Leute in mehreren Referaten/Ämtern vertreten.

**Comment by benjamin-hempel** [comment]
Erster Entwurf der Attribute für die einzelnen Klassen hinzugefügt. Bitte ansehen und ggf. Verbesserungsvorschläge einbringen @thrs79136 @creerm

**Comment by benjamin-hempel** [comment]
Bitte prüfen @thrs79136 oder @creerm

**Comment by creerm** [comment]
Ich habe mir das Klassendiagramm angeschaut und habe nichts auszusetzen. Sieht ziemlich gut aus. Man könnte noch Vorschläge für weitere Attribute der einzelnen Klassen machen, aber das ist ja nicht Sinn und Zweck derart ins Detail zu gehen nehme ich an. Von der Struktur sieht das auf jeden Fall sinnvoll aus.

**Comment by benjamin-hempel** [comment]
Alles klar, dann schließe ich die Issue erst mal. Wenn noch jemand was auszusetzen hat einfach wieder öffnen.
