### ISSUE TITLE
Nichtfunktionale Anforderungen ausarbeiten (systemwide requirements)

### ISSUE THREAD

**Issue by mribrgr** [mribrgr/StuRa-Mitgliederdatenbank#23]
Vorarbeit wurde schon geleistet. Im Detail muss es jedoch noch gemacht werden.
Zur Datei: [https://github.com/mribrgr/StuRa-Mitgliederdatenbank/blob/develop/docs/files/systemwide_regs.adoc](https://github.com/mribrgr/StuRa-Mitgliederdatenbank/blob/develop/docs/files/systemwide_regs.adoc).

**Comment by benjamin-hempel** [comment]
Duplikat von #13?

**Comment by mribrgr** [comment]
@benjamin-hempel Ja, wird entfernt.

**Comment by Yoshinonxkun** [comment]
Nein ist kein Dublikat, wurde @Stefano-96 zum Ausarbeiten zugeteilt. 
Bei der Issue #13 ging es darum sie zu erstellen und grob zu bearbeiten.

**Comment by mribrgr** [comment]
Zitat Vorlesungsfolien Praktische Hinweise zu NFAen: "Nicht-funktionale Anforderungen beeinflussen die Architektur in großem Maße -> Architekten sollten Analysten unterstützen"
