### ISSUE TITLE
Glossar fuellen

### ISSUE THREAD

**Issue by mribrgr** [mribrgr/StuRa-Mitgliederdatenbank#24]

**Comment by mribrgr** [comment]
[Link zum Glossar](https://github.com/mribrgr/StuRa-Mitgliederdatenbank/blob/develop/docs/files/glossary.adoc)

**Comment by mribrgr** [comment]
@thrs79136 hat schon bisschen vorbereitet

**Comment by thrs79136** [comment]
@Jill3 @Helene3e 
Bitte nochmal über das Glossar schauen und wenn alles in Ordnung ist das Issue schließen.

**Comment by benjamin-hempel** [comment]
@Jill3 @Helene3e 
Bitte nochmal über das Glossar schauen und wenn alles in Ordnung ist das Issue schließen
