### ISSUE TITLE
Durchschauen files\{usecases}

### ISSUE THREAD

**Issue by Yoshinonxkun** [mribrgr/StuRa-Mitgliederdatenbank#30]
Pi r quadrat halbe

**Comment by thrs79136** [comment]
@creerm
**systemwide_reqs.adoc**
* Wie oft soll ein Backup vorgenommen werden und wann sollen diese gelöscht werden? (21)
* Messung der Verfügbarkeit fehlt (45)
* Bei der Effizienz sollten Werte verwendet werden, die eine Obergrenze des Toleranzbereichs angeben (55)
* Organisatorische Randbedingungen fehlen

**Comment by thrs79136** [comment]
*Vision*
* Wie lange dauert die Bearbeitung der Aufgabe? Wie viel Zeit wird für jeden Arbeitsschritt benötigt? Ändert sich das? (fehlt)

**Comment by thrs79136** [comment]
**Iterationspläne**
* Bewertungskriterien fehlen z.T.
@mribrgr

**Comment by Yoshinonxkun** [comment]
> @creerm
> **systemwide_reqs.adoc**
> 
> * Wie oft soll ein Backup vorgenommen werden und wann sollen diese gelöscht werden? (21)
> * Messung der Verfügbarkeit fehlt (45)
> * Bei der Effizienz sollten Werte verwendet werden, die eine Obergrenze des Toleranzbereichs angeben (55)
> * Organisatorische Randbedingungen fehlen

Die Sollen von @Stefano-96 weiter Ausgearbeitet werden siehe #23 
Das mit dem Backups habe ich mir ausgedacht ich habe mir vorgestellt aller einem Monat ne komplette sicherung zu machen, die 12 Monate gespeichert wird.
