### ISSUE TITLE
!!Domänenmodell fehlt!!

### ISSUE THREAD

**Issue by Yoshinonxkun** [mribrgr/StuRa-Mitgliederdatenbank#31]
Wurde vor 6 h gepostet
https://github.com/htwdd-se/VorlageBelegabgabe/commit/198d74698a8efdf479dcc3ba0e76ab5d837d150d

Hat jemand noch reserven?

**Comment by benjamin-hempel** [comment]
Domänenmodell ist im Klassendiagramm dargestellt.

**Comment by Yoshinonxkun** [comment]
Falscher Alarm Lol refs #21
