### ISSUE TITLE
Iterationsplan für Iteration 4 erstellen

### ISSUE THREAD

**Issue by mribrgr** [mribrgr/StuRa-Mitgliederdatenbank#35]

**Comment by benjamin-hempel** [comment]
@mribrgr

**Comment by Yoshinonxkun** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Iterationspläne für Iterationen 4, 5 und 6 und 7 erstellen](https://trello.com/c/aFnOL5gA/45-iterationspl%C3%A4ne-f%C3%BCr-iterationen-4-5-und-6-und-7-erstellen)
