### ISSUE TITLE
Iterationsplan für Iteration 5 erstellen

### ISSUE THREAD

**Issue by mribrgr** [mribrgr/StuRa-Mitgliederdatenbank#36]

**Comment by benjamin-hempel** [comment]
Idee: Wie wäre es, wenn wir nach jeder Iteration eine kurze Retrospektive machen (Was lief gut? Wo gab es Probleme? Wie können wir diese vielleicht lösen?) und festlegen, was wir in der darauf folgenden Iteration schaffen wollen (ggf. auch direkt mit Wichtung nach Story Points). Würde imo die Erstellung des Projektplans vereinfachen und auch den Entwicklungsprozess unterstützen.

**Comment by Yoshinonxkun** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Iterationspläne für Iterationen 4, 5 und 6 und 7 erstellen](https://trello.com/c/aFnOL5gA/45-iterationspl%C3%A4ne-f%C3%BCr-iterationen-4-5-und-6-und-7-erstellen)
