### ISSUE TITLE
Aktivitätsdiagramme überarbeiten

### ISSUE THREAD

**Issue by Yoshinonxkun** [mribrgr/StuRa-Mitgliederdatenbank#53]
Wie ist das zu verstehen haben wir zu viel gemacht????

![image](https://user-images.githubusercontent.com/45177922/79683819-e461ad80-822c-11ea-9235-38e9c9fdfb8e.png)

zusätzlich ändern der Folgenden Diagramme:
![image](https://user-images.githubusercontent.com/45177922/79683834-00654f00-822d-11ea-8796-33c264e3f11e.png)
![image](https://user-images.githubusercontent.com/45177922/79683838-0e1ad480-822d-11ea-9d38-51653bad43e2.png)

**Comment by benjamin-hempel** [comment]
> Wie ist das zu verstehen haben wir zu viel gemacht????
So hab ich es verstanden.

**Comment by Yoshinonxkun** [comment]
Na toll ... also nehmen wir die Diagramme raus aus der Documentation?
oder eher den Text?

**Comment by benjamin-hempel** [comment]
Weiß nicht, Prof. Anke will weniger Diagramme, aber Herr Ringel ja offenbar mehr (siehe seine Mail zu unserer Architektur-Doku). Vielleicht sollten wir hier noch mal einen der beiden konsultieren.

**Comment by Yoshinonxkun** [comment]
können es ja als Frage für das nächste Treffen mit dem Stakeholder aufheben.
