### ISSUE TITLE
Instanzen holen

### ISSUE THREAD

**Issue by mribrgr** [mribrgr/StuRa-Mitgliederdatenbank#6]
Es werden Instanzen für die Entwicklung gebraucht. Die Idee war, dass dies direkt auf dem StuRa Server geschehen wird. Dazu soll zu jedem Branch ein LXC Container erstellt werden, sodass jeder direkt auf dem Server in dem Container arbeiten kann.

**Comment by mribrgr** [comment]
Anmerkung: Idee war es, das ganze mit Github issues zu verbinden

**Comment by benjamin-hempel** [comment]
Frage: Brauchen wir für die Entwicklung dringend LXC-Instanzen für jeden Branch? Wir haben ja jetzt schon lokal mit der Entwicklung angefangen. Ist der Setup-Aufwand dafür in Anbetracht der Projektgröße nicht vielleicht zu hoch?

**Comment by Yoshinonxkun** [comment]
Ich würde es auf die 3. letzte Iteration verschieben, ich denke auch nicht das wir es eher brauchen

**Comment by benjamin-hempel** [comment]
Wäre ich auch dafür.

**Comment by benjamin-hempel** [comment]
Das Deployment erfolgt mit durch den StuRa selbst bzw. mit diesem gemeinsam, deshalb werden unsererseits keine Instanzen benötigt.
