### ISSUE TITLE
files/archit_notebook.adoc

### ISSUE THREAD

**Issue by Yoshinonxkun** [mribrgr/StuRa-Mitgliederdatenbank#68]
überarbeiten der logischen Sicht

![image](https://user-images.githubusercontent.com/45177922/79690477-d88ce000-825a-11ea-9a1c-737ba085d51e.png)

**Comment by Yoshinonxkun** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Architektur Notebook bearbeiten](https://trello.com/c/5pfT2FO5/55-architektur-notebook-bearbeiten)

**Comment by benjamin-hempel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Architekturdokumentation überarbeiten](https://trello.com/c/rpnR6RFX/57-architekturdokumentation-%C3%BCberarbeiten)
