### ISSUE TITLE
Architektur Notizbuch erstellen

### ISSUE THREAD

**Issue by mribrgr** [mribrgr/StuRa-Mitgliederdatenbank#9]
Bitte im Ordner files ablegen (mit englischem Namen)

**Comment by mribrgr** [comment]
Wie sieht es aus?

**Comment by mribrgr** [comment]
Link: [Archit Notebook](https://github.com/mribrgr/StuRa-Mitgliederdatenbank/blob/develop/docs/files/archit_notebook.adoc)

**Comment by mribrgr** [comment]
Derzeitiger Stand: Klassendiagramme haben zunächst Prio

**Comment by creerm** [comment]
Architekturnotebook fertiggestellt, bitte überprüfen.
@thrs79136

**Comment by thrs79136** [comment]
@creerm 
Auf Zeile 45 ist noch ein TODO, sonst sieht alles gut aus

**Comment by creerm** [comment]
Habs korrigiert.
